RestaurantWeb/Models/ErrorViewModel.cs
namespace RestaurantWeb.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

RestaurantWeb/Models/Meniu.cs
using System.ComponentModel.DataAnnotations;

namespace RestaurantWeb.Models
{
    public class Meniu
    {
        [Key]
        public int Id { get; set; }
        [Required]
        public string Name { get; set; }
        [Required]
        public string Ingredients { get; set; }
        [Required]
        public int Price { get; set; }

    }
}

RestaurantWeb/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using RestaurantWeb.Models;
using System.Diagnostics;

namespace RestaurantWeb.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

RestaurantWeb/Controllers/MeniuController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using RestaurantWeb.Data;
using RestaurantWeb.Models;

namespace RestaurantWeb.Controllers
{
    public class MeniuController : Controller
    {
        private readonly MeniuDbContext mdb;
        public MeniuController(MeniuDbContext _mdb)
        {
            mdb = _mdb;
        }
        public IActionResult Index()
        {
            IEnumerable<Meniu> objMeniuList = mdb.menius;
            return View(objMeniuList);
        }

        //Get 
        public IActionResult Create()
        {
            return View();
        }

        //Post
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(Meniu obj)
        {
            if (obj.Name == obj.Ingredients)
            {
                ModelState.AddModelError("Name", "The Ingrediends field cannot match the Name field ");
            }
            if (ModelState.IsValid)
            {
                mdb.menius.Add(obj);
                mdb.SaveChanges();
                TempData["success"] = "Meniu added succesfully";
                return RedirectToAction("Index");
            }
            return View(obj);
        }

        public IActionResult Edit(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }
            var obj = mdb.menius.Find(id);
            if (obj == null)
            {
                return NotFound();
            }
            return View(obj);
        }

        //Post
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(Meniu obj)
        {
            if (obj.Name == obj.Ingredients)
            {
                ModelState.AddModelError("Name", "The Ingrediends field cannot match the Name field ");
            }
            if (ModelState.IsValid)
            {
                mdb.menius.Update(obj);
                mdb.SaveChanges();
                TempData["success"] = "Meniu updated succesfully";
                return RedirectToAction("Index");
            }
            return View(obj);
        }
        public IActionResult Delete(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }
            var obj = mdb.menius.Find(id);
            if (obj == null)
            {
                return NotFound();
            }
            return View(obj);
        }

        //Post
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Delete(Meniu obj)
        {
            if (obj == null)
            {
                return NotFound();
            }          
                mdb.menius.Remove(obj);
                mdb.SaveChanges();
            TempData["success"] = "Meniu deleted succesfully";
            return RedirectToAction("Index");

        }

        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var meniu = await mdb.menius
                .FirstOrDefaultAsync(m => m.Id == id);
            if (meniu == null)
            {
                return NotFound();
            }

            return View(meniu);
        }
        /*public IActionResult Details(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }
            var obj = mdb.menius.Find(id);
            if (obj == null)
            {
                return NotFound();
            }
            return View(obj);
        }*/
    }
}

RestaurantWeb/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

RestaurantWeb/Views/Meniu/Create.cshtml
@model Meniu


<form method="post">
    <div class="border p-3 mt-4">
        <div class="row pb-2">
            <h2 class="text-primary">Create Menu</h2>
            <hr />
        </div>
        <div asp-validation-summary="All"></div>
        <div class="mb-3">
            <label asp-for="Name"></label>
            <input asp-for="Name" class="form-control" />
            <span asp-validation-for="Name" class="text-danger"></span>
        </div>
        <div class="mb-3">
            <label asp-for="Ingredients"></label>
            <input asp-for="Ingredients" class="form-control" />
            <span asp-validation-for="Ingredients" class="text-danger"></span>           
        </div>
        <div class="mb-3">
            <label asp-for="Price"></label>
            <input asp-for="Price" class="form-control" />
            <span asp-validation-for="Price" class="text-danger"></span>  
        </div>
        <button type="submit" class="btn btn-primary" style="width:150px">Create</button>
        <a asp-controller="Meniu" asp-action="Index" class="btn btn-secodary" style="width:150px">Back To List</a>
    </div>
</form>

@section Scripts{
    @{
        <partial name="_ValidationScriptsPartial" />
    }
}

RestaurantWeb/Views/Meniu/Edit.cshtml
@model RestaurantWeb.Models.Meniu

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Meniu</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Ingredients" class="control-label"></label>
                <input asp-for="Ingredients" class="form-control" />
                <span asp-validation-for="Ingredients" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Price" class="control-label"></label>
                <input asp-for="Price" class="form-control" />
                <span asp-validation-for="Price" class="text-danger"></span>
            </div>
            <button type="submit" class="btn btn-success" style="width:150px">Update</button>
            <a asp-controller="Meniu" asp-action="Index" class="btn btn-primary" style="width:150px">Back To List</a>
        </form>
    </div>
</div>

@section Scripts{
    @{
        <partial name="_ValidationScriptsPartial" />
    }
}

RestaurantWeb/Views/Meniu/Index.cshtml
@model IEnumerable<Meniu>
@{
    ViewData["Title"] = "Index";
}


<div class="container p-3">
    <div class="row pt-4">
        <div class="col-6">
            <h2 class="text-primary">Menu List</h2>
        </div>
        <div class="col-6 text-end">
            <a asp-controller="Meniu" asp-action="Create" class ="btn btn-primary">
                <i class="bi bi-plus-circle"></i> &nbsp; Create New Menu
            </a>
        </div>
    </div>
    <br /><br />

<table class ="table table-bordered table-striped" style="width:100%">
    <thead>
        <tr>
            <th>
                Name
            </th>            
            <th>
                Price
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach(var obj in Model)
        {
            <tr>
                <td width>
                    @obj.Name
                </td>
                <td width>
                    @obj.Price
                </td>
                <td>
                    <div class="w-100 btn-group" role="group">
                        <a asp-controller="Meniu" asp-action="Edit" asp-route-id="@obj.Id"
                        class="btn btn-warning mx-2"> <i class="bi bi-pencil-square"></i> Edit </a>
                        <a asp-controller="Meniu" asp-action="Delete" asp-route-id="@obj.Id"
                        class="btn btn-danger mx-2"> <i class="bi bi-trash-fill"></i> Delete </a>
                        <a asp-controller="Meniu" asp-action="Details" asp-route-id="@obj.Id"
                        class="btn btn-info mx-2"> <i class="bi bi-book-half"></i> Details </a>
                    </div>
                </td>
            </tr>
        }
    </tbody>
</table>
</div>

RestaurantWeb/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - RestaurantWeb</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/RestaurantWeb.styles.css" asp-append-version="true" />
    <link rel="stylesheet" hred="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.css" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.7.2/font/bootstrap-icons.css">
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">Navbar</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarColor02" aria-controls="navbarColor02" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarColor02">
      <ul class="navbar-nav me-auto">
        <li class="nav-item">
          <a class="nav-link " asp-area="" asp-controller="Home" asp-action="Index">Home</a>
            
          </a>
        </li>
        <li class="nav-item">
          <a class="nav-link " asp-area="" asp-controller="Meniu" asp-action="Index">Meniu</a>
        </li>
        
        @*<li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" data-bs-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">Dropdown</a>
          <div class="dropdown-menu">
            <a class="dropdown-item" href="#">Action</a>
            <a class="dropdown-item" href="#">Another action</a>
            <a class="dropdown-item" href="#">Something else here</a>
            <div class="dropdown-divider"></div>
            <a class="dropdown-item" href="#">Separated link</a>
          </div>
        </li>*@
      </ul>
    </div>
  </div>
</nav>

    </header>
    <div class="container">
        <main role="main" class="pb-3">
            <partial name="_Notification" />
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - RestaurantWeb - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

RestaurantWeb/Views/Shared/_Notification.cshtml
@if(TempData["success"] != null)
{
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>
    <script type="text/javascript">
        toastr.options = {
          "closeButton": false,
          "debug": false,
          "newestOnTop": false,
          "progressBar": false,
          "positionClass": "toast-top-right",
          "preventDuplicates": false,
          "onclick": null,
          "showDuration": "300",
          "hideDuration": "1000",
          "timeOut": "5000",
          "extendedTimeOut": "1000",
          "showEasing": "swing",
          "hideEasing": "linear",
          "showMethod": "fadeIn",
          "hideMethod": "fadeOut"
        };
        toastr.success('@TempData["success"]');
    </script>
}